version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - voting-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=db
    networks:
      - voting-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=voting
      - POSTGRES_PASSWORD=votingpassword
    networks:
      - voting-network

  redis:
    image: redis:latest
    networks:
      - voting-network

networks:
  voting-network:
    driver: overlay
