version: "3"

services:
  vote:
    image: voting-app
    ports:
      - "5002:80"
    networks:
      - frontend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  result:
    image: result-app
    ports:
      - "5003:80"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  worker:
    image: worker-app
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:alpine
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend: