version: "3"

services:
  vote:
    image: dockersamples/examplevotingapp_vote:latest
    ports:
      - "5005:80"
    networks:
      - frontend

  result:
    image: dockersamples/examplevotingapp_result:latest
    ports:
      - "5006:80"
    networks:
      - backend

  worker:
    image: dockersamples/examplevotingapp_worker:latest
    networks:
      - frontend
      - backend

  redis:
    image: redis:alpine
    networks:
      - frontend

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    networks:
      - backend

networks:
  frontend:
  backend: