name: Deploy to EC2

on:
  push:
    branches:
      - main  # atau sesuaikan dengan nama branch kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: |
            docker-compose.yml
            vote/
            result/
          target: /home/ec2-user/app

      - name: Deploy stack on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /home/ec2-user/app
            docker stack deploy -c docker-compose.yml votingapp

